version: 2.1

orbs:
  act: cci-labs/act@dev:c49dc8f599f316d706747d022e13b6d549997b7b

jobs:
  build-and-publish:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - act/restore-cli
      - act/restore-actions
      # - act/restore-image
      - act/install
      - act/act:
          step-name: Login to Docker Hub
          uses: docker/login-action@v3
          with: |
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            logout: false
          secrets: "GITHUB_TOKEN,DOCKERHUB_TOKEN"
          variables: "DOCKERHUB_USERNAME"
          verbose: true
          skip-install: true
          cache-images: false
          cache-cli: false
          cache-actions: false
      - act/act:
          step-name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          skip-create-env-var-secret-files: true
          skip-install: true
          cache-images: false
          cache-cli: false
          cache-actions: false
          checkout: false
      - act/act:
          step-name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          skip-create-env-var-secret-files: true
          skip-install: true
          cache-images: false
          cache-cli: false
          cache-actions: false
          checkout: false
      - act/act:
          step-name: Build and push
          uses: docker/build-push-action@v6
          with: |
            push: true
            tags: jamescrowleyibm/sample-docker-build:circleci
          skip-create-env-var-secret-files: true
          skip-install: true
          cache-images: false
          cache-cli: false
          cache-actions: false
          checkout: false
      - act/cache-cli
      - act/cache-actions
      # - act/cache-image

workflows:
  main:
    jobs:
      - build-and-publish
      - act/act:
          skip-create-workflow-file: true
          workflow-file: .github/workflows/config.yml
          secrets: "GITHUB_TOKEN,DOCKERHUB_TOKEN"
          variables: "DOCKERHUB_USERNAME"
          cache-images: false
          cache-cli: false
          cache-actions: true
      - do-nothing:
          type: no-op
          
