version: 2.1

orbs:
  act: cci-labs/act@1.0.4

jobs:
  build-and-publish:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - act/act:
          #job-name: Login to Docker Hub
          uses: docker/login-action@v3
          with: |
            username: jamescrowleyibm
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            logout: false
          secrets: "GITHUB_TOKEN,DOCKERHUB_TOKEN"
          reuse: true
          verbose: true
          platform: ubuntu-latest=catthehacker/ubuntu:act-22.04
          cache-images: false
          action-offline-mode: true
      - act/act:
          #job-name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          secrets: "GITHUB_TOKEN,DOCKERHUB_TOKEN"
          reuse: true
          platform: ubuntu-latest=catthehacker/ubuntu:act-22.04
          skip-create-env-and-secret-file: true
          skip-install: true
          cache-images: false
          checkout: false
          action-offline-mode: true
      - act/act:
          #job-name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          secrets: "GITHUB_TOKEN,DOCKERHUB_TOKEN"
          reuse: true
          platform: ubuntu-latest=catthehacker/ubuntu:act-22.04
          skip-create-env-and-secret-file: true
          skip-install: true
          cache-images: false
          checkout: false
          action-offline-mode: true
      - act/act:
          #job-name: Build and push
          uses: docker/build-push-action@v6
          with: |
            push: true
            tags: jamescrowleyibm/sample-docker-build:circleci
          secrets: "GITHUB_TOKEN,DOCKERHUB_TOKEN"
          reuse: true
          platform: ubuntu-latest=catthehacker/ubuntu:act-22.04
          skip-create-env-and-secret-file: true
          skip-install: true
          verbose: true
          cache-images: false
          checkout: false
          action-offline-mode: true
      

workflows:
  main:
    jobs:
      - build-and-publish
      - act/act:
          skip-create-workflow-file: true
          workflow-file: .circleci/github.yml
          secrets: "GITHUB_TOKEN,DOCKERHUB_TOKEN"
          #reuse: true
          verbose: true
          platform: ubuntu-latest=catthehacker/ubuntu:act-22.04
          cache-images: false
          action-offline-mode: true